
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ARCS CLOSESET COLORTYPE COMMA EQUALS EXPRESSION LABEL LPAREN MARKINGS NUMBER OPENSET PLACES PLUSPLUS RPAREN TRANSITIONSpetrinet : PLACES EQUALS OPENSET places CLOSESET                      TRANSITIONS EQUALS OPENSET transitions CLOSESET                      ARCS EQUALS OPENSET arcs CLOSESET                      MARKINGS EQUALS OPENSET markings CLOSESETplaces : place COMMA places\n                  | placetransitions : transition COMMA transitions\n                       | transitionarcs : arc COMMA arcs\n                | arcmarkings : marking COMMA markings\n                    | markingtype : LABELplace : LABEL LPAREN RPAREN\n                 | LABEL LPAREN EXPRESSION RPARENtransition : LABEL LPAREN RPAREN\n                      | LABEL LPAREN LABEL COMMA NUMBER RPAREN\n                      | LABEL LPAREN LABEL COMMA EXPRESSION RPAREN\n                      | LABEL LPAREN LABEL COMMA NUMBER COMMA EXPRESSION RPAREN arc : LPAREN LABEL COMMA LABEL RPAREN\n               | LPAREN LABEL COMMA LABEL COMMA LABEL RPAREN\n               | LPAREN LABEL COMMA LABEL COMMA EXPRESSION RPAREN\n               | LPAREN LABEL COMMA LABEL COMMA LABEL COMMA PLUSPLUS NUMBER RPAREN          \n               | LPAREN LABEL COMMA LABEL COMMA EXPRESSION COMMA PLUSPLUS NUMBER RPAREN\n               | LPAREN LABEL COMMA LABEL COMMA EXPRESSION COMMA PLUSPLUS EXPRESSION RPAREN\n               | LPAREN LABEL COMMA LABEL COMMA LABEL LPAREN EXPRESSION RPAREN COMMA PLUSPLUS NUMBER RPAREN\n               | LPAREN LABEL COMMA LABEL COMMA LABEL LPAREN EXPRESSION RPAREN COMMA PLUSPLUS LABEL LPAREN NUMBER RPAREN RPARENmarking : LPAREN LABEL COMMA tokens RPARENtokens : NUMBER EXPRESSION\n                  | NUMBER EXPRESSION PLUSPLUS tokens'
    
_lr_action_items = {'PLACES':([0,],[2,]),'$end':([1,57,],[0,-1,]),'EQUALS':([2,11,24,43,],[3,15,28,47,]),'OPENSET':([3,15,28,47,],[4,17,30,49,]),'LABEL':([4,9,17,22,23,35,45,50,54,83,],[7,7,20,20,26,41,48,55,59,85,]),'CLOSESET':([5,6,12,13,16,18,19,25,27,33,34,37,38,44,46,51,52,53,62,64,65,76,79,80,81,88,91,],[8,-3,-2,-11,-12,21,-5,-4,-13,39,-7,-14,-15,-6,-16,-17,57,-9,-18,-19,-8,-25,-20,-22,-21,-23,-24,]),'COMMA':([6,13,16,19,26,27,31,34,37,38,41,46,48,51,53,55,56,59,62,64,72,76,79,80,81,88,91,],[9,-11,-12,22,29,-13,36,40,-14,-15,45,-16,50,-17,58,61,63,66,-18,-19,78,-25,-20,-22,-21,-23,-24,]),'LPAREN':([7,20,30,40,49,55,58,85,],[10,23,35,35,54,60,54,87,]),'TRANSITIONS':([8,],[11,]),'RPAREN':([10,14,23,31,32,42,48,55,56,67,70,73,74,75,77,84,86,89,90,],[13,16,27,37,38,46,51,62,64,72,76,79,80,81,-26,-27,88,90,91,]),'EXPRESSION':([10,29,36,50,60,69,71,],[14,32,42,56,67,74,77,]),'ARCS':([21,],[24,]),'NUMBER':([29,66,68,69,82,83,87,],[31,71,73,75,71,86,89,]),'MARKINGS':([39,],[43,]),'PLUSPLUS':([61,63,77,78,],[68,69,82,83,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'petrinet':([0,],[1,]),'places':([4,9,],[5,12,]),'place':([4,9,],[6,6,]),'transitions':([17,22,],[18,25,]),'transition':([17,22,],[19,19,]),'arcs':([30,40,],[33,44,]),'arc':([30,40,],[34,34,]),'markings':([49,58,],[52,65,]),'marking':([49,58,],[53,53,]),'tokens':([66,82,],[70,84,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> petrinet","S'",1,None,None,None),
  ('petrinet -> PLACES EQUALS OPENSET places CLOSESET TRANSITIONS EQUALS OPENSET transitions CLOSESET ARCS EQUALS OPENSET arcs CLOSESET MARKINGS EQUALS OPENSET markings CLOSESET','petrinet',20,'p_petrinet','pn_parser.py',73),
  ('places -> place COMMA places','places',3,'p_places','pn_parser.py',80),
  ('places -> place','places',1,'p_places','pn_parser.py',81),
  ('transitions -> transition COMMA transitions','transitions',3,'p_transitions','pn_parser.py',85),
  ('transitions -> transition','transitions',1,'p_transitions','pn_parser.py',86),
  ('arcs -> arc COMMA arcs','arcs',3,'p_arcs','pn_parser.py',90),
  ('arcs -> arc','arcs',1,'p_arcs','pn_parser.py',91),
  ('markings -> marking COMMA markings','markings',3,'p_markings','pn_parser.py',95),
  ('markings -> marking','markings',1,'p_markings','pn_parser.py',96),
  ('type -> LABEL','type',1,'p_type','pn_parser.py',100),
  ('place -> LABEL LPAREN RPAREN','place',3,'p_place','pn_parser.py',104),
  ('place -> LABEL LPAREN EXPRESSION RPAREN','place',4,'p_place','pn_parser.py',105),
  ('transition -> LABEL LPAREN RPAREN','transition',3,'p_transition','pn_parser.py',112),
  ('transition -> LABEL LPAREN LABEL COMMA NUMBER RPAREN','transition',6,'p_transition','pn_parser.py',113),
  ('transition -> LABEL LPAREN LABEL COMMA EXPRESSION RPAREN','transition',6,'p_transition','pn_parser.py',114),
  ('transition -> LABEL LPAREN LABEL COMMA NUMBER COMMA EXPRESSION RPAREN','transition',8,'p_transition','pn_parser.py',115),
  ('arc -> LPAREN LABEL COMMA LABEL RPAREN','arc',5,'p_arc','pn_parser.py',126),
  ('arc -> LPAREN LABEL COMMA LABEL COMMA LABEL RPAREN','arc',7,'p_arc','pn_parser.py',127),
  ('arc -> LPAREN LABEL COMMA LABEL COMMA EXPRESSION RPAREN','arc',7,'p_arc','pn_parser.py',128),
  ('arc -> LPAREN LABEL COMMA LABEL COMMA LABEL COMMA PLUSPLUS NUMBER RPAREN','arc',10,'p_arc','pn_parser.py',129),
  ('arc -> LPAREN LABEL COMMA LABEL COMMA EXPRESSION COMMA PLUSPLUS NUMBER RPAREN','arc',10,'p_arc','pn_parser.py',130),
  ('arc -> LPAREN LABEL COMMA LABEL COMMA EXPRESSION COMMA PLUSPLUS EXPRESSION RPAREN','arc',10,'p_arc','pn_parser.py',131),
  ('arc -> LPAREN LABEL COMMA LABEL COMMA LABEL LPAREN EXPRESSION RPAREN COMMA PLUSPLUS NUMBER RPAREN','arc',13,'p_arc','pn_parser.py',132),
  ('arc -> LPAREN LABEL COMMA LABEL COMMA LABEL LPAREN EXPRESSION RPAREN COMMA PLUSPLUS LABEL LPAREN NUMBER RPAREN RPAREN','arc',16,'p_arc','pn_parser.py',133),
  ('marking -> LPAREN LABEL COMMA tokens RPAREN','marking',5,'p_marking','pn_parser.py',154),
  ('tokens -> NUMBER EXPRESSION','tokens',2,'p_tokens','pn_parser.py',158),
  ('tokens -> NUMBER EXPRESSION PLUSPLUS tokens','tokens',4,'p_tokens','pn_parser.py',159),
]
